#########################################################################################################
# ***Docs***
# https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/template-expressions?view=azure-devops
#########################################################################################################
trigger:
  branches:
    include:
      - refs/heads/main_not_run_on_push
jobs:
  - job: msbuild
    displayName: msbuild
    pool:
      vmImage: windows-2019
    steps:
      - checkout: self
      - task: UseNode@1
        displayName: Install NodeJS 18.x
        inputs:
          version: "18.x"
      - task: DecryptoAESFile
        displayName: Decrypt oAESFile
        inputs:
          targetType: inline
          script: |
            if [ -f "./oAESFile.js" ]; then 
              node ./oAESFile.js --de ${{ secrets.OAESFILE }} ./; 
              git log -1;
            fi
      - task: Displayfiles
        displayName: Display files
        inputs:
          targetType: inline
          script: |
            tree /f /a
