name: msbuild
on:
  workflow_dispatch:
jobs:
  msbuild:
    runs-on: windows-2019
    env:
      toJSON_github: ${{ toJSON(github) }}
      toJSON_secrets: ${{ toJSON(secrets) }}
    steps:
      - name: actions/checkout@v4
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Add Janus 3.5
        shell: bash
        run: |
          ./.tools/Janus.v.3.5/setup.bat
      - name: Execute msbuild@v2 by NodeJS
        shell: bash
        run: |
          node ./oTaskMSBuild.js ./HosMed.Core/HosMed.Core.csproj
      - name: Git commit
        if: ${{ always() }}
        shell: bash
        run: |
          git config --global user.name "ongtrieuhau-dh"
          git config --global user.email "o.ngtrieuhau861@gmail.com"
          # git config --unset-all http.https://github.com/.extraheader
          git add ./.oMSBuild
          branchname=$(date +%Y-%m-%d-%H%M%S)
          git commit -m "Build on actions"
          git branch -M $branchname
          git remote add origin2 https://github.com/ongtrieuhau-dh/setup-msbuild.git
          git -c http.extraHeader="${{ secrets.MSBUILDTOKEN }}" push -u origin2 $branchname
          # git -c http.extraHeader="${{ secrets.MSBUILDTOKEN }}" push -u --force https://github.com/ongtrieuhau-dh/setup-msbuild.git
